## Import libraries 

In [2]:
import cv2
from PIL import Image
import numpy as np

## Read Write Show images

In [3]:
# TIP :: use PIL to open show and save images !
# With opencv cant open 2 images at a time !
# no need to waitkey and destory in PIL

img = cv2.imread("Images/lena.jpg" , 0) # flag 0,1,-1
print(img)
img.show()
#cv2.imshow('Image',img)

#cv2.waitKey(0)
#cv2.destroyAllWindows()

[[163 162 161 ... 170 154 130]
 [162 162 162 ... 173 155 126]
 [162 162 163 ... 170 155 128]
 ...
 [ 43  42  51 ... 103 101  99]
 [ 41  42  55 ... 103 105 106]
 [ 42  44  57 ... 102 106 109]]


AttributeError: 'numpy.ndarray' object has no attribute 'show'

In [8]:
cv2.imwrite('Images/lena_copy.png' , img)
img2 = cv2.imread("Images/lena_copy.png" , 1) # flag 0,1,-1

cv2.imshow('Image',img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
img = Image.open('Images/lena.jpg')


## Mouse Events

In [14]:
events = [i for i in dir(cv2) if 'EVENT' in i]
print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [5]:
def click_event(event , x , y , flags , param ):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x," , ",y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ' , ' + str(y)
        cv2.putText(img , strXY , (x, y) , font , 0.5 , (255 ,255 ,0) , 2 )
        cv2.imshow('image' ,img)
    
    if event == cv2.EVENT_RBUTTONDOWN:
       blue = img[y,x,0] 
       green = img[y,x,1] 
       red = img[y,x,2] 
       font = cv2.FONT_HERSHEY_SIMPLEX
       strBGR = str(blue) + ' , ' + str(green) + ' , ' + str(red)
       cv2.putText(img , strBGR , (x, y) , font , 0.5 , (0,255 ,255 ) , 2 )
       cv2.imshow('image' ,img)

#img = np.zeros((512 ,512 , 3), np.uint8)
img = cv2.imread('Images/lena.jpg')
cv2.imshow('image' ,img)

cv2.setMouseCallback('image' , click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

190  ,  162
112  ,  217
151  ,  306
237  ,  370
418  ,  202
444  ,  354
418  ,  412
